(() => {
  'use strict';
  const API_BASE='https://n8n-pi.taild8d05f.ts.net/webhook';
  const VIEW_URL=`${API_BASE}/workplan-time-plan`;
  const SAVE_URL=`${API_BASE}/workplan-time-plan-save`;
  const STORAGE_KEY='workplan_user';
  const parse=(raw)=>{try{return JSON.parse(raw||'null')}catch{return null}};
  const user=parse(sessionStorage.getItem(STORAGE_KEY))||parse(localStorage.getItem(STORAGE_KEY));
  if(!user?.userId){location.replace('index.html');return;}
  const canEdit=['admin','leader'].includes(String(user.role||'').toLowerCase());
  const els={date:document.getElementById('planDate'),shiftStrip:document.getElementById('shiftStrip'),demandGrid:document.getElementById('demandGrid'),plannerRows:document.getElementById('plannerRows'),message:document.getElementById('pageMessage'),search:document.getElementById('employeeSearch'),shiftDrawer:document.getElementById('shiftDrawer'),shiftBackdrop:document.getElementById('shiftBackdrop'),shiftCount:document.getElementById('shiftCount'),shiftRows:document.getElementById('shiftEditorRows'),shiftMessage:document.getElementById('shiftMessage')};
  const state={data:null};
  const display=user.displayName||user.login||'Użytkownik';
  document.getElementById('userDisplay').textContent=display;
  document.getElementById('userAvatar').textContent=display.trim().charAt(0).toUpperCase()||'U';
  document.getElementById('logoutBtn').onclick=()=>{sessionStorage.removeItem(STORAGE_KEY);localStorage.removeItem(STORAGE_KEY);location.replace('index.html')};
  document.getElementById('menuToggle')?.addEventListener('click',()=>document.body.classList.toggle('nav-open'));
  const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Warsaw'});
  const fmtHours=n=>Number(n||0).toLocaleString('pl-PL',{maximumFractionDigits:2});
  const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
  function shiftDuration(s){const [a,b]=s.startTime.split(':').map(Number),[c,d]=s.endTime.split(':').map(Number);let x=c*60+d-(a*60+b);if(x<=0)x+=1440;return x/60;}
  function setSummary(){const d=state.data;document.getElementById('summaryShifts').textContent=d?.summary?.activeShifts??0;document.getElementById('summaryRequired').textContent=fmtHours(d?.summary?.requiredHours);document.getElementById('summaryAssigned').textContent=fmtHours(d?.summary?.assignedHours);document.getElementById('summaryEmployees').textContent=d?.summary?.plannedEmployees??0;}
  function renderShifts(){const shifts=state.data?.shifts||[];els.shiftStrip.innerHTML=shifts.length?shifts.map(s=>`<button class="shift-card" type="button" data-shift="${s.shiftNo}"><div><span>Zmiana ${s.shiftNo}</span><strong>${esc(s.name)}</strong></div><div><time>${esc(s.startTime)}–${esc(s.endTime)}</time><span>${fmtHours(shiftDuration(s))} h</span></div></button>`).join(''):'<div class="shift-card empty"><strong>Brak konfiguracji zmian</strong><span>Ustaw przynajmniej jedną zmianę dla tego dnia.</span></div>';els.shiftStrip.querySelectorAll('[data-shift]').forEach(b=>b.onclick=openShiftDrawer)}
  function equalSplit(total,count){if(!count)return[];const base=Math.floor((total/count)*100)/100;const out=Array(count).fill(base);out[count-1]=Math.round((total-out.slice(0,-1).reduce((a,b)=>a+b,0))*100)/100;return out}
  function renderDemand(){const shifts=state.data?.shifts||[], demand=state.data?.demand||[];els.demandGrid.innerHTML=demand.map(d=>{const current=d.shiftParts?.length?d.shiftParts.map(x=>Number(x.requiredHours||0)):equalSplit(Number(d.totalHours||0),shifts.length);const perShift=shifts.map((s,i)=>`<label><span>Z${s.shiftNo}</span><input type="number" min="0" step="0.25" data-shift-hours="${s.shiftNo}" value="${current[i]??0}" ${canEdit?'':'disabled'}></label>`).join('');const cls=d.status==='ok'?'ok':'shortage';const txt=d.status==='ok'?`Obsada OK · +${fmtHours(d.gapHours)} h`:`Brakuje ${fmtHours(Math.abs(d.gapHours))} h`;return `<article class="demand-card" data-process="${esc(d.processId)}"><div class="process-name"><strong>${esc(d.name)}</strong><span>${d.requiredPeople} os. przy ${fmtHours(d.defaultHoursPerPerson)} h/os.</span></div><div class="metric-input"><label>Godziny / dzień</label><input type="number" min="0" step="0.25" data-total-hours value="${Number(d.totalHours||0)}" ${canEdit?'':'disabled'}></div><div class="metric-input"><label>h / osobę</label><input type="number" min="0.25" max="24" step="0.25" data-person-hours value="${Number(d.defaultHoursPerPerson||8)}" ${canEdit?'':'disabled'}></div><div class="shift-hours">${perShift}</div><div class="coverage ${cls}"><strong>${fmtHours(d.assignedHours)} / ${fmtHours(d.totalHours)} h</strong><span>${txt}</span></div><button class="secondary-button demand-save" type="button" ${canEdit?'':'disabled'}>Zapisz</button></article>`}).join('');
    els.demandGrid.querySelectorAll('.demand-card').forEach(card=>{const total=card.querySelector('[data-total-hours]');const shiftInputs=[...card.querySelectorAll('[data-shift-hours]')];total.addEventListener('change',()=>{const split=equalSplit(Number(total.value||0),shiftInputs.length);shiftInputs.forEach((i,idx)=>i.value=split[idx]??0)});card.querySelector('.demand-save').onclick=()=>saveDemand(card)});
  }
  function planFor(userId){return (state.data?.plans||[]).find(p=>p.userId===userId)}
  function renderPlanner(){const q=els.search.value.trim().toLowerCase(), employees=(state.data?.employees||[]).filter(e=>!q||`${e.displayName} ${e.login}`.toLowerCase().includes(q));const processes=state.data?.processes||[],shifts=state.data?.shifts||[];els.plannerRows.innerHTML=employees.map(e=>{const p=planFor(e.userId),proc=p?.processId||processes[0]?.processId||'',shiftNo=p?.shiftNo||shifts[0]?.shiftNo||1,s=shifts.find(x=>x.shiftNo===shiftNo)||shifts[0];const start=p?.startTime||s?.startTime||'06:00',end=p?.endTime||s?.endTime||'14:00';return `<tr data-user="${esc(e.userId)}"><td><div class="person-cell"><strong>${esc(e.displayName)}</strong><span>${e.role==='leader'?'Lider':'Pracownik'}</span></div></td><td><select data-process ${canEdit?'':'disabled'}>${processes.map(x=>`<option value="${esc(x.processId)}" ${x.processId===proc?'selected':''}>${esc(x.name)}</option>`).join('')}</select></td><td><select data-shift ${canEdit?'':'disabled'}>${shifts.map(x=>`<option value="${x.shiftNo}" ${x.shiftNo===shiftNo?'selected':''}>Zmiana ${x.shiftNo}</option>`).join('')}</select></td><td><input data-start type="time" value="${start}" ${canEdit?'':'disabled'}></td><td><input data-end type="time" value="${end}" ${canEdit?'':'disabled'}></td><td class="planner-hours" data-hours>${fmtHours(calcHours(start,end))} h</td><td><span class="status-dot">${p?'Zaplanowany':'Brak planu'}</span></td><td><button class="secondary-button" data-save type="button" ${canEdit?'':'disabled'}>Zapisz</button></td></tr>`}).join('');
    els.plannerRows.querySelectorAll('tr[data-user]').forEach(row=>{const refresh=()=>row.querySelector('[data-hours]').textContent=`${fmtHours(calcHours(row.querySelector('[data-start]').value,row.querySelector('[data-end]').value))} h`;row.querySelector('[data-start]').onchange=refresh;row.querySelector('[data-end]').onchange=refresh;row.querySelector('[data-shift]').onchange=()=>{const s=shifts.find(x=>x.shiftNo===Number(row.querySelector('[data-shift]').value));if(s){row.querySelector('[data-start]').value=s.startTime;row.querySelector('[data-end]').value=s.endTime;refresh()}};row.querySelector('[data-save]').onclick=()=>savePlan(row)});
  }
  function calcHours(a,b){if(!a||!b)return 0;const [h1,m1]=a.split(':').map(Number),[h2,m2]=b.split(':').map(Number);let x=h2*60+m2-(h1*60+m1);if(x<=0)x+=1440;return x/60}
  async function apiSave(payload){els.message.textContent='Zapisywanie…';const body=new URLSearchParams({...payload,requestedBy:user.userId,date:els.date.value});const r=await fetch(SAVE_URL,{method:'POST',body,cache:'no-store',credentials:'omit'});const data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error(data.message||'Nie udało się zapisać.');els.message.textContent=data.message||'Zapisano.';await load()}
  async function saveDemand(card){try{const shiftHours=[...card.querySelectorAll('[data-shift-hours]')].map(i=>({shiftNo:Number(i.dataset.shiftHours),requiredHours:Number(i.value||0)}));await apiSave({action:'demand',processId:card.dataset.process,totalHours:card.querySelector('[data-total-hours]').value,defaultHoursPerPerson:card.querySelector('[data-person-hours]').value,shiftHours:JSON.stringify(shiftHours)})}catch(e){els.message.textContent=e.message}}
  async function savePlan(row){try{await apiSave({action:'plan',userId:row.dataset.user,processId:row.querySelector('[data-process]').value,shiftNo:row.querySelector('[data-shift]').value,startTime:row.querySelector('[data-start]').value,endTime:row.querySelector('[data-end]').value,status:'active'})}catch(e){els.message.textContent=e.message}}
  function openShiftDrawer(){if(!canEdit)return;const shifts=state.data?.shifts||[];els.shiftCount.value=String(Math.max(1,shifts.length||1));renderShiftEditors();els.shiftBackdrop.hidden=false;els.shiftDrawer.classList.add('open')}
  function closeShiftDrawer(){els.shiftBackdrop.hidden=true;els.shiftDrawer.classList.remove('open')}
  function renderShiftEditors(){const count=Number(els.shiftCount.value),current=state.data?.shifts||[];els.shiftRows.innerHTML=Array.from({length:count},(_,i)=>{const no=i+1,s=current.find(x=>x.shiftNo===no),defaults=[['06:00','14:00'],['14:00','22:00'],['22:00','06:00'],['06:00','18:00'],['18:00','06:00'],['08:00','16:00']][i];return `<div class="shift-edit-row" data-no="${no}"><div class="shift-number">Z${no}</div><input class="shift-name" type="text" maxlength="80" value="${esc(s?.name||`Zmiana ${no}`)}"><input data-start type="time" value="${s?.startTime||defaults[0]}"><input data-end type="time" value="${s?.endTime||defaults[1]}"></div>`}).join('')}
  async function saveShifts(event){event.preventDefault();els.shiftMessage.textContent='';const shifts=[...els.shiftRows.querySelectorAll('.shift-edit-row')].map(r=>({shiftNo:Number(r.dataset.no),name:r.querySelector('.shift-name').value.trim(),startTime:r.querySelector('[data-start]').value,endTime:r.querySelector('[data-end]').value,active:true}));try{await apiSave({action:'shifts',shifts:JSON.stringify(shifts)});closeShiftDrawer()}catch(e){els.shiftMessage.textContent=e.message}}
  async function load(){els.message.textContent='';const r=await fetch(`${VIEW_URL}?date=${encodeURIComponent(els.date.value)}`,{cache:'no-store',credentials:'omit'});const data=await r.json().catch(()=>({}));if(!r.ok||!data.ok)throw new Error(data.message||'Nie udało się pobrać planu.');state.data=data;setSummary();renderShifts();renderDemand();renderPlanner()}
  async function safeLoad(){try{await load()}catch(e){els.message.textContent=e.message}}
  function moveDay(delta){const d=new Date(`${els.date.value}T12:00:00`);d.setDate(d.getDate()+delta);els.date.value=d.toISOString().slice(0,10);safeLoad()}
  els.date.value=today();els.date.onchange=safeLoad;document.getElementById('prevDay').onclick=()=>moveDay(-1);document.getElementById('nextDay').onclick=()=>moveDay(1);document.getElementById('todayBtn').onclick=()=>{els.date.value=today();safeLoad()};document.getElementById('configureShiftsBtn').onclick=openShiftDrawer;document.getElementById('shiftDrawerClose').onclick=closeShiftDrawer;document.getElementById('shiftCancel').onclick=closeShiftDrawer;els.shiftBackdrop.onclick=closeShiftDrawer;els.shiftCount.onchange=renderShiftEditors;document.getElementById('shiftForm').onsubmit=saveShifts;els.search.oninput=renderPlanner;if(!canEdit)document.getElementById('configureShiftsBtn').disabled=true;
  safeLoad();
})();
